services:
  backend:
    container_name: uprag-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - backend/app/.env.development
    networks:
      - appnet
    volumes:
      - ./backend:/work
  frontend:
    container_name: uprag-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - appnet
networks:
  appnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
